### ISSUE TITLE
Dockerize Our Fork Of Mozilla Spoke

### ISSUE THREAD

**Issue by shawticus** [xrchat/xrchat-ops#1]
https://github.com/xrchat/Spoke

**Comment by mfouad** [comment]
I already did some work here: https://github.com/xrchat/Spoke/blob/k8s/Dockerfile
I will document and issue a pull request
@dmitrizagidulin @barankyle

**Comment by dmitrizagidulin** [comment]
Thanks @mfouad! (In case it's helpful, there's also https://github.com/xrchat/mozilla-hubs-docker, which includes a Docker file for Hubs and Spoke together).

**Comment by dmitrizagidulin** [comment]
Hey @mfouad - just to double check, did this make it into a PR?

**Comment by shawticus** [comment]
@mfouad housekeeping on this. Will leave open, deployment is obviously priority.

**Comment by mrhegemon** [comment]
Previous work. Needs to only be spoke. No reticulum no client.
 https://github.com/xrchat/mozilla-hubs-docker
